/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "counter.v:1" *)
module counter(clk, rst, en, count);
  (* src = "counter.v:4" *)
  wire [1:0] _00_;
  wire _01_;
  wire _02_;
  wire _03_;
  wire _04_;
  wire _05_;
  wire _06_;
  wire _07_;
  wire _08_;
  wire _09_;
  (* src = "counter.v:2" *)
  input clk;
  (* src = "counter.v:3" *)
  output [1:0] count;
  (* src = "counter.v:2" *)
  input en;
  (* src = "counter.v:2" *)
  input rst;
  NAND _10_ (
    .A(_07_),
    .B(_09_),
    .Y(_05_)
  );
  NAND _11_ (
    .A(_08_),
    .B(_05_),
    .Y(_06_)
  );
  NOR _12_ (
    .A(_04_),
    .B(_06_),
    .Y(_00_[1])
  );
  NOT _13_ (
    .A(count[1]),
    .Y(_07_)
  );
  NOT _14_ (
    .A(rst),
    .Y(_08_)
  );
  NAND _15_ (
    .A(en),
    .B(count[0]),
    .Y(_09_)
  );
  NOR _16_ (
    .A(en),
    .B(count[0]),
    .Y(_01_)
  );
  NOR _17_ (
    .A(rst),
    .B(_01_),
    .Y(_02_)
  );
  NAND _18_ (
    .A(_09_),
    .B(_02_),
    .Y(_03_)
  );
  NOT _19_ (
    .A(_03_),
    .Y(_00_[0])
  );
  NOR _20_ (
    .A(_07_),
    .B(_09_),
    .Y(_04_)
  );
  (* src = "counter.v:4" *)
  DFF _21_ (
    .C(clk),
    .D(_00_[0]),
    .Q(count[0])
  );
  (* src = "counter.v:4" *)
  DFF _22_ (
    .C(clk),
    .D(_00_[1]),
    .Q(count[1])
  );
endmodule
