/* Generated by Yosys 0.9 (git sha1 UNKNOWN, clang 12.0.0 -fPIC -Os) */

(* top =  1  *)
(* src = "foo.v:1" *)
module foo(a, b, c, o);
  (* src = "foo.v:2" *)
  wire _0_;
  (* src = "foo.v:3" *)
  wire _1_;
  (* src = "foo.v:4" *)
  wire _2_;
  wire _3_;
  wire _4_;
  (* src = "foo.v:5" *)
  wire _5_;
  (* src = "foo.v:8" *)
  wire _6_;
  (* src = "foo.v:2" *)
  input a;
  (* src = "foo.v:3" *)
  input b;
  (* src = "foo.v:4" *)
  input c;
  (* src = "foo.v:5" *)
  output o;
  NOT _7_ (
    .A(_2_),
    .Y(_3_)
  );
  NAND _8_ (
    .A(_0_),
    .B(_1_),
    .Y(_4_)
  );
  NAND _9_ (
    .A(_3_),
    .B(_4_),
    .Y(_5_)
  );
  assign _0_ = a;
  assign _1_ = b;
  assign _2_ = c;
  assign o = _5_;
endmodule
